<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Beranda extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Profil_model');
        $this->load->model('Produk_model');
        $this->load->model('Artikel_model');
    }

    /*
     * Listing of bongkar_log
     */
    function index()
    {
        $data['profil'] = $this->Profil_model->detail_data(1);
        $data['produk'] = $this->Produk_model->produk_minimal(6);
        $data['artikel'] = $this->Artikel_model->semua_data();
        $data['_view'] = 'front/beranda';
        $this->load->view('_layouts/front/index',$data);
    }

}