<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Pengiriman_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get pengiriman by idPengiriman
     */
    function get_pengiriman($idPengiriman)
    {
        return $this->db->get_where('pengiriman',array('idPengiriman'=>$idPengiriman))->row_array();
    }

    /*
     * Get all pengiriman
     */
    function get_all_pengiriman()
    {
        return $this->db->get('pengiriman')->result_array();
    }

    /*
     * function to add new pengiriman
     */
    function add_pengiriman($params)
    {
        $this->db->insert('pengiriman',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update pengiriman
     */
    function update_pengiriman($idPengiriman,$params)
    {
        $this->db->where('idPengiriman',$idPengiriman);
        $response = $this->db->update('pengiriman',$params);
        if($response)
        {
            return "pengiriman updated successfully";
        }
        else
        {
            return "Error occuring while updating pengiriman";
        }
    }

    /*
     * function to delete pengiriman
     */
    function delete_pengiriman($idPengiriman)
    {
        $response = $this->db->delete('pengiriman',array('idPengiriman'=>$idPengiriman));
        if($response)
        {
            return "Pengiriman deleted successfully";
        }
        else
        {
            return "Error occuring while deleting pengiriman";
        }
    }

}

?>